# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltlogin_set', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='userid',
        ),
        migrations.AddField(
            model_name='user',
            name='poke',
            field=models.ManyToManyField(related_name='_user_poke_+', to='beltlogin_set.User'),
        ),
        migrations.DeleteModel(
            name='Appt',
        ),
    ]
